CREATE TABLE cpu (
  id                 int(11) NOT NULL, 
  name               varchar(255), 
  model              text, 
  clock              text, 
  max_turbo          text, 
  integrated_gpu     text, 
  stock_cooler       tinyint(1), 
  manufacturer       text, 
  cpu_series         text, 
  logical_cores      int(11), 
  physical_cores     int(11), 
  socket             text, 
  superscore         int(11), 
  avg_critic_score   int(11), 
  avg_user_score     int(11), 
  oldest_review_date date, 
  newest_review_date date, 
  PRIMARY KEY (id));
CREATE TABLE gpu (
  id                     int(11) NOT NULL, 
  name                   varchar(255), 
  model                  text, 
  processor_manufacturer text, 
  manufacturer           text, 
  graphic_processor      text, 
  mem_size               text, 
  boosted_clock          text, 
  superscore             int(11), 
  avg_critic_score       int(11), 
  avg_user_score         int(11), 
  oldest_review_date     date, 
  newest_review_date     date, 
  PRIMARY KEY (id));
CREATE TABLE review (
  id         int(11) NOT NULL, 
  product_id int(11), 
  `date`     date, 
  is_critic  tinyint(1), 
  url        varchar(255) NOT NULL UNIQUE, 
  title      text NOT NULL, 
  author     varchar(255), 
  rating     float, 
  content    mediumtext, 
  PRIMARY KEY (id));
