CREATE TABLE criticReview (ProductID int(10) NOT NULL, ID int(10) NOT NULL AUTO_INCREMENT, title text NOT NULL, `review rating` int(10), `product rating` int(10), `date` text, upvote int(10), downvote int(10), PRIMARY KEY (ID));
CREATE TABLE Product (ID int(10) NOT NULL AUTO_INCREMENT, Name int(10), Manufacturer int(10), PRIMARY KEY (ID));
CREATE TABLE Product_Retailer (ProductID int(10) NOT NULL, RetailerID int(10) NOT NULL, price double, url text, PRIMARY KEY (ProductID, RetailerID));
CREATE TABLE `critic-Pros` (pro text, criticReviewID int(10) NOT NULL);
CREATE TABLE `critic-Cons` (con text, criticReviewID int(10) NOT NULL);
CREATE TABLE userReview (ID int(10) NOT NULL AUTO_INCREMENT, ProductID int(10) NOT NULL, name text, title text NOT NULL, content text, rating double, upvotes int(10), downvotes int(10), `date` date, credibility int(10), PRIMARY KEY (ID));
CREATE TABLE `user-pros` (con text, userReviewID int(10) NOT NULL);
CREATE TABLE `user-cons` (pro text, userReviewID int(10) NOT NULL);
CREATE TABLE Retailer (ID int(10) NOT NULL AUTO_INCREMENT, name text, PRIMARY KEY (ID));
CREATE TABLE Product2 (ID int(11) NOT NULL AUTO_INCREMENT, descritopn text, imagePath text, name varchar(255) NOT NULL, PRIMARY KEY (ID));
CREATE TABLE GPU (ProductID2 int(10) NOT NULL, processorManufacturer text, chipset text, model text, architecture text, cooling text, memSize text, pciSlots int(10));
CREATE TABLE CPU (model text, clock text, MaxTurbo text, integratedGpu text, stockCooler bit(1), manufacturer text, cpuType text, logicalCores int(11), physicalCores int(11), ProductID2 int(10) NOT NULL);
CREATE TABLE Motherboard (ProductID2 int(10) NOT NULL, fromFactor text, cpuType text, cpuCount int(11), socket text, netCard bit(1), soundCard bit(1), multiGPU bit(1), crossfire bit(1), sli bit(1), maxMem int(11), memSlots int(11), memType text, graphicsCard bit(1));
CREATE TABLE Cooling (ProductID2 int(10) NOT NULL, type text, speed text, `size` text, airflow text, noice text, connector text);
CREATE TABLE Chassis (ProductID2 int(10) NOT NULL, type text, atx bit(1), miniAtx bit(1), miniItx bit(1), fans int(11), brand text, height text, width text, depth text, weight text);
CREATE TABLE SoundCard (ProductID2 int(10) NOT NULL, type text, speakerSupport text, socket text, fullDuplex text);
CREATE TABLE RAM (ProductID2 int(10) NOT NULL, capacity text, technology text, formFactor text, speed text, casLatens text, type text);
CREATE TABLE PSU (ProductID2 int(10) NOT NULL, power text, format text, modular bit(1), width text, Depth text, height text, weight text, brand text);
CREATE TABLE HardDrive (ProductID2 int(10) NOT NULL, isInternal bit(1), type text, formFactor text, capacity text, cacheSize text, transforRate text, brand text, sata text, height text, depth text, width text);
ALTER TABLE criticReview ADD INDEX `reviews of product` (ProductID), ADD CONSTRAINT `reviews of product` FOREIGN KEY (ProductID) REFERENCES Product (ID);
ALTER TABLE Product_Retailer ADD INDEX `is sold by` (ProductID), ADD CONSTRAINT `is sold by` FOREIGN KEY (ProductID) REFERENCES Product (ID);
ALTER TABLE `critic-Pros` ADD INDEX `list of pros` (criticReviewID), ADD CONSTRAINT `list of pros` FOREIGN KEY (criticReviewID) REFERENCES criticReview (ID);
ALTER TABLE `critic-Cons` ADD INDEX `list of cons` (criticReviewID), ADD CONSTRAINT `list of cons` FOREIGN KEY (criticReviewID) REFERENCES criticReview (ID);
ALTER TABLE userReview ADD INDEX `reviewed product` (ProductID), ADD CONSTRAINT `reviewed product` FOREIGN KEY (ProductID) REFERENCES Product (ID);
ALTER TABLE Product_Retailer ADD INDEX `sells product` (RetailerID), ADD CONSTRAINT `sells product` FOREIGN KEY (RetailerID) REFERENCES Retailer (ID);
ALTER TABLE GPU ADD INDEX FKGPU737124 (ProductID2), ADD CONSTRAINT FKGPU737124 FOREIGN KEY (ProductID2) REFERENCES Product (ID);
ALTER TABLE CPU ADD INDEX FKCPU733280 (ProductID2), ADD CONSTRAINT FKCPU733280 FOREIGN KEY (ProductID2) REFERENCES Product (ID);
ALTER TABLE Motherboard ADD INDEX FKMotherboar247126 (ProductID2), ADD CONSTRAINT FKMotherboar247126 FOREIGN KEY (ProductID2) REFERENCES Product (ID);
ALTER TABLE Cooling ADD INDEX FKCooling429724 (ProductID2), ADD CONSTRAINT FKCooling429724 FOREIGN KEY (ProductID2) REFERENCES Product (ID);
ALTER TABLE Chassis ADD INDEX FKChassis545284 (ProductID2), ADD CONSTRAINT FKChassis545284 FOREIGN KEY (ProductID2) REFERENCES Product (ID);
ALTER TABLE SoundCard ADD INDEX FKSoundCard620150 (ProductID2), ADD CONSTRAINT FKSoundCard620150 FOREIGN KEY (ProductID2) REFERENCES Product (ID);
ALTER TABLE RAM ADD INDEX FKRAM747222 (ProductID2), ADD CONSTRAINT FKRAM747222 FOREIGN KEY (ProductID2) REFERENCES Product (ID);
ALTER TABLE PSU ADD INDEX FKPSU745866 (ProductID2), ADD CONSTRAINT FKPSU745866 FOREIGN KEY (ProductID2) REFERENCES Product (ID);
ALTER TABLE HardDrive ADD INDEX FKHardDrive263006 (ProductID2), ADD CONSTRAINT FKHardDrive263006 FOREIGN KEY (ProductID2) REFERENCES Product (ID);
ALTER TABLE `user-cons` ADD INDEX `FKuser-cons499036` (userReviewID), ADD CONSTRAINT `FKuser-cons499036` FOREIGN KEY (userReviewID) REFERENCES userReview (ID);
ALTER TABLE `user-pros` ADD INDEX `FKuser-pros889233` (userReviewID), ADD CONSTRAINT `FKuser-pros889233` FOREIGN KEY (userReviewID) REFERENCES userReview (ID);
